version: 1

workspace_configs:
  - name: template-default-repository-spacelift
    terraform_version: "1.5.0"
    autoformat: true
    autodeploy: true
    
    # Add project root and workspace settings
    project_root: "."
    workspace: "default"
    
    # Add environment settings
    environment:
      - TF_CLI_ARGS_init: "-backend=false"
      - TF_IN_AUTOMATION: "true"
      - TF_WORKSPACE: "default"
    
    # Define the build and deployment process
    before_init:
      - npm install -g nx@latest
    
    before_apply:
      - npm ci
      - npx nx build hatch_project --configuration=production
    
    # Define the deployment process
    deployment:
      steps:
        - name: Deploy to GitHub Pages
          run: |
            REPO_NAME=$(echo "$GITHUB_REPOSITORY" | cut -d'/' -f2)
            
            # Update asset paths
            sed -i "s|<base href=\"/\"|<base href=\"/$REPO_NAME/\"|g" dist/apps/hatch_project/index.html
            sed -i "s|src=\"/assets|src=\"/$REPO_NAME/assets|g" dist/apps/hatch_project/index.html
            sed -i "s|href=\"/assets|href=\"/$REPO_NAME/assets|g" dist/apps/hatch_project/index.html
            
            # Deploy using GitHub Pages action
            uses: peaceiris/actions-gh-pages@v3
            with:
              github_token: ${{ secrets.GITHUB_TOKEN }}
              publish_dir: ./dist/apps/hatch_project