name: Spacelift Deployment

on:
  push:
    branches:
      - main
    paths:
      - '.spacelift/**'
      - 'main.tf'
      - 'policies/**'

jobs:
  spacelift:
    runs-on: ubuntu-latest
    # Skip if other workflows are handling deployment
    if: "!contains(github.event.head_commit.message, '[skip spacelift]')"
    steps:
      - uses: actions/checkout@v3
